routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\Auth\Admin\AuthenticatedSessionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;

//--------------------------------Authentication Routes-------------------------------------------//
Route::group(['prefix' => 'admin', 'middleware' => 'guest:admin'],function() {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('admin.login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);
});
Route::get('admin/logout',[AuthenticatedSessionController::class,'destroy'])
    ->name('admin.logout')->middleware('auth:admin');
//------------------------------End Authentication Routes-----------------------------------------//


//------------------------------Dashboard Routes-----------------------------------------//
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:admin'],function(){
    Route::get('dashboard',[AdminDashboardController::class,'index'])->name('dashboard');


    Route::resource('products', ProductController::class);
    Route::get('products/{id}/trash', 'App\Http\Controllers\ProductController@trash')->name('products.trash');
    Route::post('products/mass/trash', 'App\Http\Controllers\ProductController@massTrash')->name('products.mass.trash');
    Route::post('products/mass/destroy', 'App\Http\Controllers\ProductController@massDestroy')->name('products.mass.destroy');
    Route::get('products/empty/trash', 'App\Http\Controllers\ProductController@emptyTrash')->name('products.trash.empty');
    Route::get('products/{id}/restore', 'App\Http\Controllers\ProductController@restore')->name('products.restore');
    Route::post('products/mass/restore', 'App\Http\Controllers\ProductController@massRestore')->name('products.mass.restore');
    Route::get('trash/products', 'App\Http\Controllers\ProductController@trashed')->name('products.trashed');


    Route::resource('categories', CategoryController::class);
    Route::post('categories/mass/destroy', 'App\Http\Controllers\CategoryController@massDestroy')->name('categories.mass.destroy');

});
//----------------------------End Dashboard Routes---------------------------------------//

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';
require __DIR__.'/admin.php';

app/Models/Category.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes, Sluggable;

    protected $fillable = ['name', 'description', 'slug', 'active'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Http\Requests\Category\CreateCategoryRequest;
use App\Models\Category;
use App\Repositories\Category\CategoryRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    private $category;
    private $model;

    public function __construct(CategoryRepository $category){
        $this->model = trans('app.model.category');
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->all();

        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateCategoryRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateCategoryRequest $request)
    {
        $this->category->store($request);

        return redirect(route('admin.categories.index'))->with('success', trans('messages.created', ['model' => $this->model]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->find($id);

        return view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCategoryRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $this->category->update($request, $id);

        return redirect(route('admin.categories.index'))->with('success',trans('messages.updated', ['model' => $this->model]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $this->category->destroy($id);

        return redirect(route('admin.categories.index'))->with('success',trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function massDestroy(Request $request)
    {
        $this->category->massDestroy(explode(',',$request->ids));

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>Dashboard</h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                                <li><a href="{{ route('admin.categories.index') }}">Categories</a></li>
                                <li class="active">Add New</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="content">

        @include('admin.category.form')

    </div>

@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>Dashboard</h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                                <li><a href="{{ route('admin.categories.index') }}">Categories</a></li>
                                <li class="active">Edit Category</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="content">

        @include('admin.category.form')

    </div>

@endsection

resources/views/admin/category/form.blade.php
<div class="row">

    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><strong>Category</strong><small> Form</small></div>
            <div class="card-body card-block">
                <form action="{{ isset($category)?route('admin.categories.update',$category->id):route('admin.categories.store') }}" method="post" enctype="multipart/form-data">
                    @if(isset($category))
                        @method('patch')
                    @endif
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name" class=" form-control-label">Category Name</label>
                                <input name="name" value="{{ $category->name??old('name') }}" type="text" placeholder="Enter your category name" class="form-control @error('name') {{ "is-invalid" }} @enderror" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="model" class=" form-control-label">Active/Inactive</label>
                                <div>
                                    <div class="form-check-inline form-check">
                                        <label for="inline-radio1" class="form-check-label ">
                                            <input type="radio" name="active" value="1" class="form-check-input" {{ isset($category)?($category->active?'checked':''):(old('active')?'checked':'')}}>Active
                                        </label>
                                        <label for="inline-radio2" class="form-check-label ">
                                            <input type="radio" name="active" value="0" class="form-check-input" {{ isset($category)?($category->active?'':'checked'):(old('active')?'':'checked')}}>Inactive
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description" class=" form-control-label">Category Description</label>
                        <textarea name="description" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{!! $category->description??old('description') !!}</textarea>
                    </div>
                    <div class="form-group">
                        <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                            <i class="fa fa-plus fa-lg"></i>&nbsp;
                            <span id="payment-button-amount">{{isset($category) ? 'Update ' :'Add '}}Category Now</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

resources/views/admin/category/index.blade.php
@extends('layouts.admin')

@section('stylesheet')
    {{--Datatable CSS--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    {{--Exporter CSS--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
@endsection

@section('content')

    <div class="content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Categories Table</h4>
                            @include('messages')
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="category-table" class="table">
                                    <thead class=" text-primary">
                                    <th><input type="checkbox" id="select-all"></th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $category)
                                        <tr>
                                            <td><input type="checkbox" data-id="{{ $category->id }}" class="ind-check"></td>
                                            <td>
                                                {{ $category->id }}
                                            </td>
                                            <td class="text-primary">
                                                {{ $category->name }}
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.categories.edit',$category->id) }}">Edit</a> |
                                                <a href="{{ route('admin.categories.destroy',$category->id) }}" id="deleteButton">Permanently Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <form method="post" id="deleteForm">
        @csrf
        @method('delete')
    </form>
    <form action="{{ route('admin.categories.mass.destroy') }}" method="post" id="mass-destroy-form">
        @csrf
        <input type="hidden" name="ids" id="mass-destroy-ids">
    </form>
@endsection

@section('script')
    {{--Datatable Script--}}
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    {{--Exporter Script--}}
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>

    <script>
        jQuery(document).ready(function() {
            jQuery('a#deleteButton').click(function(e){
                e.preventDefault();
                let action = jQuery(this).attr('href');
                if(confirm('Are you sure you want to permanently delete the selected category?'))
                    jQuery('#deleteForm').attr('action',action).submit();
            });
            jQuery('#select-all:checkbox').click(function(){
                if(jQuery(this).is(':checked'))
                    jQuery('.ind-check').prop('checked',true);
                else
                    jQuery('.ind-check').prop('checked',false);
            });
            jQuery('#category-table').DataTable({
                "scrollY": 500,
                dom: 'Bfrtip',
                buttons: [{
                    text: 'Mass Delete',
                    action: function ( e, dt, node, config ) {
                        let ids = [];
                        jQuery('.ind-check:checkbox').each(function(){
                            if(jQuery(this).is(':checked'))
                                ids.push(jQuery(this).data('id'));
                        });
                        if(ids.length === 0){
                            alert('No Categories is selected in the current window!');
                            return ;
                        }
                        if(confirm('Are you sure you want to permanently delete the selected categories?')){
                            massDestroy(ids);
                        }
                    }
                },'excel', 'pdf', 'print','pageLength']
            });
            function massDestroy(ids){
                jQuery('#mass-destroy-ids').val(ids);
                jQuery('#mass-destroy-form').submit();
            }
        });
    </script>
@endsection