routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\Auth\Admin\AuthenticatedSessionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;

//--------------------------------Authentication Routes-------------------------------------------//
Route::group(['prefix' => 'admin', 'middleware' => 'guest:admin'],function() {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('admin.login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);
});
Route::get('admin/logout',[AuthenticatedSessionController::class,'destroy'])
    ->name('admin.logout')->middleware('auth:admin');
//------------------------------End Authentication Routes-----------------------------------------//


//------------------------------Dashboard Routes-----------------------------------------//
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:admin'],function(){
    Route::get('dashboard',[AdminDashboardController::class,'index'])->name('dashboard');


    Route::resource('products', ProductController::class);
    Route::get('products/{id}/trash', 'App\Http\Controllers\ProductController@trash')->name('products.trash');
    Route::post('products/mass/trash', 'App\Http\Controllers\ProductController@massTrash')->name('products.mass.trash');
    Route::post('products/mass/destroy', 'App\Http\Controllers\ProductController@massDestroy')->name('products.mass.destroy');
    Route::get('products/empty/trash', 'App\Http\Controllers\ProductController@emptyTrash')->name('products.trash.empty');
    Route::get('products/{id}/restore', 'App\Http\Controllers\ProductController@restore')->name('products.restore');
    Route::post('products/mass/restore', 'App\Http\Controllers\ProductController@massRestore')->name('products.mass.restore');
    Route::get('trash/products', 'App\Http\Controllers\ProductController@trashed')->name('products.trashed');


    Route::resource('categories', CategoryController::class);
    Route::post('categories/mass/destroy', 'App\Http\Controllers\CategoryController@massDestroy')->name('categories.mass.destroy');

});
//----------------------------End Dashboard Routes---------------------------------------//

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';
require __DIR__.'/admin.php';

app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\Imageable;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, Imageable, SoftDeletes, Sluggable;

    protected $fillable = ['name','description','active','brand','model','price','slug'];

    /**
     * Get all categories of the product
     * @return BelongsToMany
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Models\Product;
use App\Repositories\Product\ProductRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{

    private $product;
    private $model;

    public function __construct(ProductRepository $product){
        $this->model = trans('app.model.product');
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->product->all();
        return view('admin.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateProductRequest $request
     * @return RedirectResponse
     */
    public function store(CreateProductRequest $request)
    {
        $this->product->store($request);

        return redirect(route('admin.products.index'))->with('success', trans('messages.created', ['model' => $this->model]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $id
     * @return string
     */
    public function edit($id)
    {
        $product = $this->product->find($id,['categories','images']);
        $preview = $product->getPreviewData($product->images);

        return view('admin.products.edit',compact('product','preview'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $id
     * @return RedirectResponse
     */
    public function update(UpdateProductRequest $request, $id)
    {
        $this->product->update($request,$id);

        return redirect(route('admin.products.index'))->with('success',trans('messages.updated', ['model' => $this->model]));
    }

    /**
     * Put in trash
     * @param Request $request
     * @param $id
     */
    public function trash(Request $request, $id){
        $this->product->trash($id);

        return back()->with('success',trans('messages.trashed',['model' => $this->model]));
    }

    /**
     * View all trashed products
     */
    public function trashed(){
        $trashedProducts = $this->product->trashOnly();

        return view('admin.products.trash',compact('trashedProducts'));
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function restore($id)
    {
        $this->product->restore($id);

        return back()->with('success', trans('messages.restored', ['model' => $this->model]));
    }

    public function massRestore(Request $request)
    {
        $this->product->massRestore(explode(',',$request->ids));

        return back()->with('success', trans('messages.restored', ['model' => $this->model]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $this->product->destroy($id);

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function massTrash(Request $request)
    {
        $this->product->massTrash(explode(',',$request->ids));

        return back()->with('success', trans('messages.trashed', ['model' => $this->model]));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function massDestroy(Request $request)
    {
        $this->product->massDestroy(explode(',',$request->ids));

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function emptyTrash()
    {
        $this->product->emptyTrash();

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.admin')

@section('stylesheet')
    <link rel="stylesheet" href="{{ asset('admin/css/lib/chosen/chosen.min.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Bootstrap Fileinput -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">

@endsection

@section('content')

    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>Dashboard</h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                                <li><a href="{{ route('admin.products.index') }}">Products</a></li>
                                <li class="active">Add New</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="animated fadeIn">

            @include('admin.products.form')

        </div>
    </div>

@endsection

@section('script')
    <script src="{{ asset('admin/js/lib/chosen/chosen.jquery.min.js') }}"></script>
    <!-- Bootstrap Fileinput -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js" type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/themes/fas/theme.min.js"></script>
    <script>
        jQuery("#input-id").fileinput({
            theme: "fas",
        });
        jQuery(document).ready(function() {
            jQuery(".standardSelect").chosen({
                disable_search_threshold: 10,
                no_results_text: "Oops, nothing found!",
                width: "100%"
            });
        });
    </script>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.admin')

@section('stylesheet')
    <link rel="stylesheet" href="{{ asset('admin/css/lib/chosen/chosen.min.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Bootstrap Fileinput -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
@endsection

@section('content')

    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>Dashboard</h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                                <li><a href="{{ route('admin.products.index') }}">Products</a></li>
                                <li class="active">Edit Product</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="animated fadeIn">

            @include('admin.products.form')

        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('admin/js/lib/chosen/chosen.jquery.min.js') }}"></script>
    <!-- Bootstrap Fileinput -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js" type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/themes/fas/theme.min.js"></script>

    <script>
        let url = 'https://www.nepalhighlandtreks.com/uploads/gallery/potala-palace1.jpg';
        jQuery("#input-id").fileinput({
            initialPreview: @json($preview['preview']),
            initialPreviewConfig: @json($preview['previewConfig']),
            initialPreviewAsData: true,
            theme: "fas",
            overwriteInitial: false,
            deleteUrl: "/api/admin/image/delete",
            ajaxDeleteSettings: { headers: {"Authorization" : "Bearer "+@json(Cookie::get('access_token'))} },
            mergeAjaxDeleteCallbacks : 'before',
        });
        jQuery(document).ready(function() {
            jQuery(".standardSelect").chosen({
                disable_search_threshold: 10,
                no_results_text: "Oops, nothing found!",
                width: "100%"
            });
        });
    </script>
@endsection

resources/views/admin/products/form.blade.php
<div class="row">

    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><strong>Product</strong><small> Form</small></div>
            <div class="card-body card-block">
                <form action="{{ isset($product)?route('admin.products.update',$product->id):route('admin.products.store') }}" method="post" enctype="multipart/form-data">
                    @if(isset($product))
                        @method('patch')
                    @endif
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name" class=" form-control-label">Product Name</label>
                                <input name="name" value="{{ $product->name??old('name') }}" type="text" placeholder="Enter your product name" class="form-control @error('name') {{ "is-invalid" }} @enderror" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price" class=" form-control-label">Price</label>
                                <div class="input-group">
                                    <div class="input-group-addon">NRs.</div>
                                    <input type="number" value="{{ $product->price??old('price') }}" name="price" placeholder="Enter Price Here" class="form-control" required>
                                    <div class="input-group-addon">.00</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="brand" class=" form-control-label">Brand Name</label>
                                <input type="text" value="{{ $product->brand??old('brand') }}" name="brand" placeholder="Enter Brand Name" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="model" class=" form-control-label">Model Name</label>
                                <input type="text" value="{{ $product->model??old('model') }}" name="model" placeholder="Enter Model Name" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description" class=" form-control-label">Product Description</label>
                        <textarea name="description" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{!! $product->description??old('description') !!}</textarea>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="street" class="form-control-label">Select Categories</label>
                                <select name="categories[]" data-placeholder="Press here to choose categories" multiple class="standardSelect">
                                    <option value="" label="default"></option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ in_array($category->id,old('categories')??(isset($product)?$product->categories->pluck('id')->toArray():[]))?'selected':'' }}>{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="model" class=" form-control-label">Active/Inactive</label>
                                <div>
                                    <div class="form-check-inline form-check">
                                        <label for="inline-radio1" class="form-check-label ">
                                            <input type="radio" name="active" value="1" class="form-check-input" {{ isset($product)?($product->active?'checked':''):(old('active')?'checked':'')}}>Active
                                        </label>
                                        <label for="inline-radio2" class="form-check-label ">
                                            <input type="radio" name="active" value="0" class="form-check-input" {{ isset($product)?($product->active?'':'checked'):(old('active')?'':'checked')}}>Inactive
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group file-loading">
                        <label for="description" class=" form-control-label">Image</label>
                        <input name="images[]" id="input-id" type="file" class="file file-loading" data-preview-file-type="text" multiple>
                    </div>
                    <div class="form-group">
                        <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                            <i class="fa fa-plus fa-lg"></i>&nbsp;
                            <span id="payment-button-amount">{{isset($product) ? 'Update ' :'Add '}}Product Now</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

resources/views/admin/products/trash.blade.php
@extends('layouts.admin')

@section('stylesheet')
    {{--Datatable CSS--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    {{--Exporter CSS--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Products Table</h4>
                            @include('messages')
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="product-table" class="table">
                                    <thead class=" text-primary">
                                    <th><input type="checkbox" id="select-all"></th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                    </thead>
                                    <tbody>
                                    @foreach($trashedProducts as $product)
                                        <tr>
                                            <td><input type="checkbox" data-id="{{ $product->id }}" class="ind-check"></td>
                                            <td>
                                                {{ $product->id }}
                                            </td>
                                            <td class="text-primary">
                                                {{ $product->name }}
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.products.restore',$product->id) }}">Restore</a> |
                                                <a href="{{ route('admin.products.destroy',$product->id) }}" id="deleteButton">Permanently Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form method="post" id="deleteForm">
        @csrf
        @method('delete')
    </form>
    <form action="{{ route('admin.products.mass.restore') }}" method="post" id="mass-restore-form">
        @csrf
        <input type="hidden" name="ids" id="mass-restore-ids">
    </form>
    <form action="{{ route('admin.products.trash.empty') }}" method="get" id="empty-trash-form">
        @csrf
    </form>
    <form action="{{ route('admin.products.mass.destroy') }}" method="post" id="mass-destroy-form">
        @csrf
        <input type="hidden" name="ids" id="mass-destroy-ids">
    </form>
@endsection
@section('script')
    {{--Datatable Script--}}
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    {{--Exporter Script--}}
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script>
        jQuery(document).ready(function(){
            jQuery('#product-table').DataTable({
                "scrollY": 500,
                dom: 'Bfrtip',
                buttons: [{
                    text: 'Mass Restore',
                    action: function ( e, dt, node, config ) {
                        let ids = getIds();
                        if(ids.length === 0){
                            alert('No Products is selected in the current window!');
                            return ;
                        }
                        if(confirm('Are you sure you want to restore the selected products?')){
                            massRestore(ids);
                        }
                    }
                },{
                    text: 'Mass Delete',
                    action: function ( e, dt, node, config ) {
                        let ids = getIds();
                        if(ids.length === 0){
                            alert('No Products is selected in the current window!');
                            return ;
                        }
                        if(confirm('Are you sure you want to permanently delete the selected products?')){
                            massDestroy(ids);
                        }
                    }
                },{
                    text: 'Empty Trash',
                    action: function ( e, dt, node, config ) {
                        if(confirm('Are you sure you want to permanently delete the selected products?')){
                            jQuery('#empty-trash-form').submit();
                        }
                    }
                },'excel', 'pdf', 'print','pageLength']
            });
            jQuery('a#deleteButton').click(function(e){
                e.preventDefault();
                let action = jQuery(this).attr('href');
                if(confirm('Are you sure you want to permanently delete the selected product?'))
                    jQuery('#deleteForm').attr('action',action).submit();
            });
            jQuery('#select-all:checkbox').click(function(){
                if(jQuery(this).is(':checked'))
                    jQuery('.ind-check').prop('checked',true);
                else
                    jQuery('.ind-check').prop('checked',false);
            });
            function massRestore(ids){
                jQuery('#mass-restore-ids').val(ids);
                jQuery('#mass-restore-form').submit();
            }
            function massDestroy(ids){
                jQuery('#mass-destroy-ids').val(ids);
                jQuery('#mass-destroy-form').submit();
            }
            function getIds(){
                let ids = [];
                jQuery('.ind-check:checkbox').each(function(){
                    if(jQuery(this).is(':checked'))
                        ids.push(jQuery(this).data('id'));
                });
                return ids;
            }
        })
    </script>
@endsection